"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

[aws]
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = "ï˜ "
format = " [$symbol$branch]($style) "

[git_status]
conflicted = "ğŸ³"
ahead = "â‡¡${count} "
behind = "â‡£${count} "
diverged = "â‡•â‡¡${ahead_count} â‡£${behind_count} "
untracked = "?${count} "
stashed = "\U0001f4e6${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "Â»${count} "
deleted = "âœ˜${count} "
style = "yellow"
format = '([$all_status$ahead_behind]($style) )'

[python]
pyenv_prefix = ""
version_format = "${major}.${minor}"
style = "green"

[rust]
version_format = "v${major}.${minor}"

[package]
disabled = true

